version: "3.8"
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-latest}"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ${PWD}/clickhouse-config/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/clickhouse-config/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
