version: "3.8"
services:
  clickhouse:
    container_name: clickhouse
    image: "clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-latest}"
    user: "101:101"
    hostname: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - ${PWD}/config/clickhouse-config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/config/clickhouse-users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:${ELASTICSEARCH_VERSION:-latest}"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
volumes:
  clickhouse_data:
    driver: local
  elasticsearch_data:
    driver: local
